### ISSUE TITLE
doesn't compile

### ISSUE THREAD

**Issue by MinecrasfsftMan** [fredespo/PNG2NAM#1]
It keeps giving me this message: error: 
```
module not found: javafx.fxml
error: module not found: javafx.controls
2 errors
```

**Comment by MinecrasfsftMan** [comment]
fixed, had to download a special version of Java.

**Comment by fredespo** [comment]
Hey @MinecrasfsftMan sorry I didn't see your initial post. I haven't touched this project in a while. I'm curious about some of the details of the solution here: what special version of Java did you need?
